data:
  root_dir: "/zdisk/users/ext_user_03/01_yschoi/project_01_FVH_detection/01_data/05_flair_preproc_slices_compressed"
  num_workers: 0
  stratified_split: true   # stratified split 사용 여부
  undersample: true

model:
  backbone: resnet18
  in_channels: 1
  pretrained: false
  transformer:                 # Transformer 관련 설정 추가
    enabled: true              # Transformer 사용 여부
    num_layers: 2              # Encoder layer 개수 (작게 시작)
    d_model: 256               # hidden dimension
    nhead: 4                   # multi-head attention head 수
    dim_feedforward: 1024      # feedforward dimension
    dropout: 0.1               # dropout 비율
    pooling: attention              # "mean", "cls", "max" 중 선택

train:
  batch_size: 8
  epochs: 100
  lr: 1.0e-3
  weight_decay: 1.0e-4
  optimizer: adamw
  scheduler: cosine
  step_size: 20
  gamma: 0.1
  warmup_epochs: 3
  amp: true
  seed: 42
  pos_weight_auto: true
  gpus: 2

ddp:
  enabled: false
  backend: nccl

out:
  output_dir: runs/resnet_transformer7_test
